return {
	Air = { HumanoidState = "Freefall" },
	Landed = { HumanoidState = "Running" },
	Jumping = { HumanoidState = "Jumping" },

	WallRunL = { "18115220361", Enum.AnimationPriority.Movement, false },
	WallRunR = { "18115215814", Enum.AnimationPriority.Movement, false },
	Running = { "114503260001308", Enum.AnimationPriority.Movement, false },
	Slide = { "125871650490956", Enum.AnimationPriority.Action, false },
	Vaulting = { "101927950911917", Enum.AnimationPriority.Action3, true },
}
